swagger: "2.0"
info:
  title: "dp-release-calendar-api"
  description: "API for managing the release calendar"
  version: 1.0.0
  license:
    name: "Open Government Licence v3.0"
    url: "http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/"
basePath: "/v1"
schemes:
  - http
tags:
  - name: "private"
  - name: "public"
paths:
  /releases/legacy:
    get:
      tags:
        - public
      summary: "Get a legacy release calendar"
      description: "Returns a release calendar entry stored in Zebedee"
      parameters:
        - $ref: '#/parameters/url'
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/ReleaseCalendarEntry"
        404:
          $ref: '#/responses/NotFound'
        500:
          $ref: '#/responses/InternalError'

  /health:
    get:
      tags:
        - private
      summary: "Returns API's health status"
      description: "Returns health status of the API and checks on dependent services"
      produces:
        - application/json
      responses:
        200:
          description: "Successfully returns OK status with checks of dependent services"
          schema:
            $ref: "#/definitions/Health"
        429:
          description: "Services warming up or degraded (at least one check in WARNING or CRITICAL status)"
        500:
          $ref: "#/responses/InternalError"

responses:
  InternalError:
    description: "Failed to process the request due to an internal error"
  NotFound:
    description: "URL not found"

parameters:
  url:
    name: url
    description: The url for the legacy release calendar entry.
    type: string
    required: true
    in: query

definitions:
  ReleaseCalendarEntry:
    type: object
    properties:
      markdown:
        type: array
        description: "Markdwon"
        items:
          type: string
      related_documents:
        type: array
        description: "Related documents"
        items:
         $ref: '#/definitions/Link'
      related_datasets:
        type: array
        description: "Related datasets"
        items:
         $ref: '#/definitions/Link'
      related_api_datasets:
        type: array
        description: "Related API datasets"
        items:
         $ref: '#/definitions/Link'
      related_methodology:
        type: array
        description: "Related methodology"
        items:
         $ref: '#/definitions/Link'
      related_methodology_article:
        type: array
        description: "Related methodology article"
        items:
         $ref: '#/definitions/Link'
      links:
        type: array
        description: "Links"
        items:
         $ref: '#/definitions/Link'
      date_changes:
        type: array
        description: "Release date changes"
        items:
         $ref: '#/definitions/ReleaseDateChange'
      uri:
        type: string
        example: "/releases/earningsandemploymentfrompayasyouearnrealtimeinformationukfebruary2022"
      description:
        type: object
        properties:
          title:
            type: string
            description: "Release title"
          summary:
            type: string
            description: "Release description"
          contact:
            type: object
            description: "Release contact"
            properties:
              name:
                type: string
                description: "Contact name"
              email:
                type: string
                description: "Contact email"
              telephone:
                type: string
                description: "Contact telephone number"
          national_statistic:
            type: boolean
            description: "Indicates if it refers to a national statistic"
          welsh_statistic:
            type: boolean
            description: "Indicates if it refers to a Welsh statistic"
          survey:
            type: string
            description: "Indicates the survey this release belongs to, if any"
            example: "census"
          release_date:
            type: string
            format: "date-time"
            description: "Release date"
          next_release:
            type: string
            description: "Next release date"
          published:
            type: boolean
            description: "Indicates if it is a published release"
          finalised:
            type: boolean
            description: "Indicates if it is a finalised release"
          cancelled:
            type: boolean
            description: "Indicates if it is a cancelled release"
          cancellation_notice:
            type: array
            description: "Cancellation notices"
            items:
              type: string
          provisional_date:
            type: string
            description: "Provisional date"
  Link:
    type: object
    properties:
      title:
        type: string
        description: "Title"
      summary:
        type: string
        description: "Summary"
      uri:
        type: string
        description: "URI"
  ReleaseDateChange:
    type: object
    properties:
      previous_date:
        type: string
        format: "date-time"
        description: "Date of change"
      change_notice:
        type: string
        description: "Change notice"
  Health:
    type: object
    properties:
      status:
        type: string
        description: "The status of the API"
        enum: ["OK", "WARNING", "CRITICAL"]
      version:
        type: object
        properties:
          build_time:
            type: string
            description: "The build date and time of the API"
            example: "2020-06-11T12:49:20+01:00"
          git_commit:
            type: string
            description: "The git commit hash of the API"
            example: "7c2febbf2b818175112478d4ffbadbee1b654f63"
          language:
            type: string
            description: "The programming language used to implement API"
            example: "go"
          language_version:
            type: string
            description: "The version of the programming language used to implement API"
            example: "go1.14.3"
          version:
            type: string
            description: "The version of API"
            example: "1.0.0"
      uptime:
        type: string
        description: "The uptime of API"
        example: "34516"
      start_time:
        type: string
        description: "The start date and time of API running"
        example: "2020-06-11T11:49:21.520922Z"
      checks:
        type: array
        items:
          $ref: '#/definitions/HealthChecker'
  HealthChecker:
    type: object
    properties:
      name:
        type: string
        description: "The name of external service used by API"
        enum: ["mongodb"]
      status:
        type: string
        description: "The status of the external service"
        enum: ["OK", "WARNING", "CRITICAL"]
      message:
        type: string
        description: "The message status of the external service"
        example: "mongodb is OK"
      last_checked:
        type: string
        description: "The last health check date and time of the external service"
        example: "2020-06-11T11:49:50.330089Z"
      last_success:
        type: string
        description: "The last successful health check date and time of the external service"
        example: "2020-06-11T11:49:50.330089Z"
      last_failure:
        type: string
        description: "The last failed health check date and time of the external service"
        example: "2019-09-22T11:48:51.0000001Z"