---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.24.4-bullseye

inputs:
  - name: dp-release-calendar-api

outputs:
  - name: build

caches:
  - path: go/

run:
  path: dp-release-calendar-api/ci/scripts/build.sh
