// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package api

import (
	"context"
	"github.com/ONSdigital/dp-api-clients-go/v2/zebedee"
	"github.com/ONSdigital/dp-healthcheck/healthcheck"
	"sync"
)

// Ensure, that ZebedeeClientMock does implement ZebedeeClient.
// If this is not the case, regenerate this file with moq.
var _ ZebedeeClient = &ZebedeeClientMock{}

// ZebedeeClientMock is a mock implementation of ZebedeeClient.
//
// 	func TestSomethingThatUsesZebedeeClient(t *testing.T) {
//
// 		// make and configure a mocked ZebedeeClient
// 		mockedZebedeeClient := &ZebedeeClientMock{
// 			CheckerFunc: func(ctx context.Context, check *healthcheck.CheckState) error {
// 				panic("mock out the Checker method")
// 			},
// 			GetReleaseFunc: func(ctx context.Context, userAccessToken string, collectionID string, lang string, uri string) (zebedee.Release, error) {
// 				panic("mock out the GetRelease method")
// 			},
// 		}
//
// 		// use mockedZebedeeClient in code that requires ZebedeeClient
// 		// and then make assertions.
//
// 	}
type ZebedeeClientMock struct {
	// CheckerFunc mocks the Checker method.
	CheckerFunc func(ctx context.Context, check *healthcheck.CheckState) error

	// GetReleaseFunc mocks the GetRelease method.
	GetReleaseFunc func(ctx context.Context, userAccessToken string, collectionID string, lang string, uri string) (zebedee.Release, error)

	// calls tracks calls to the methods.
	calls struct {
		// Checker holds details about calls to the Checker method.
		Checker []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Check is the check argument value.
			Check *healthcheck.CheckState
		}
		// GetRelease holds details about calls to the GetRelease method.
		GetRelease []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserAccessToken is the userAccessToken argument value.
			UserAccessToken string
			// CollectionID is the collectionID argument value.
			CollectionID string
			// Lang is the lang argument value.
			Lang string
			// URI is the uri argument value.
			URI string
		}
	}
	lockChecker    sync.RWMutex
	lockGetRelease sync.RWMutex
}

// Checker calls CheckerFunc.
func (mock *ZebedeeClientMock) Checker(ctx context.Context, check *healthcheck.CheckState) error {
	if mock.CheckerFunc == nil {
		panic("ZebedeeClientMock.CheckerFunc: method is nil but ZebedeeClient.Checker was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Check *healthcheck.CheckState
	}{
		Ctx:   ctx,
		Check: check,
	}
	mock.lockChecker.Lock()
	mock.calls.Checker = append(mock.calls.Checker, callInfo)
	mock.lockChecker.Unlock()
	return mock.CheckerFunc(ctx, check)
}

// CheckerCalls gets all the calls that were made to Checker.
// Check the length with:
//     len(mockedZebedeeClient.CheckerCalls())
func (mock *ZebedeeClientMock) CheckerCalls() []struct {
	Ctx   context.Context
	Check *healthcheck.CheckState
} {
	var calls []struct {
		Ctx   context.Context
		Check *healthcheck.CheckState
	}
	mock.lockChecker.RLock()
	calls = mock.calls.Checker
	mock.lockChecker.RUnlock()
	return calls
}

// GetRelease calls GetReleaseFunc.
func (mock *ZebedeeClientMock) GetRelease(ctx context.Context, userAccessToken string, collectionID string, lang string, uri string) (zebedee.Release, error) {
	if mock.GetReleaseFunc == nil {
		panic("ZebedeeClientMock.GetReleaseFunc: method is nil but ZebedeeClient.GetRelease was just called")
	}
	callInfo := struct {
		Ctx             context.Context
		UserAccessToken string
		CollectionID    string
		Lang            string
		URI             string
	}{
		Ctx:             ctx,
		UserAccessToken: userAccessToken,
		CollectionID:    collectionID,
		Lang:            lang,
		URI:             uri,
	}
	mock.lockGetRelease.Lock()
	mock.calls.GetRelease = append(mock.calls.GetRelease, callInfo)
	mock.lockGetRelease.Unlock()
	return mock.GetReleaseFunc(ctx, userAccessToken, collectionID, lang, uri)
}

// GetReleaseCalls gets all the calls that were made to GetRelease.
// Check the length with:
//     len(mockedZebedeeClient.GetReleaseCalls())
func (mock *ZebedeeClientMock) GetReleaseCalls() []struct {
	Ctx             context.Context
	UserAccessToken string
	CollectionID    string
	Lang            string
	URI             string
} {
	var calls []struct {
		Ctx             context.Context
		UserAccessToken string
		CollectionID    string
		Lang            string
		URI             string
	}
	mock.lockGetRelease.RLock()
	calls = mock.calls.GetRelease
	mock.lockGetRelease.RUnlock()
	return calls
}
